src/DinoCompareBundle/Entity/DinoData.php
<?php

namespace DinoCompareBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * DinoData
 *
 * @ORM\Table(name="dino_data")
 * @ORM\Entity(repositoryClass="DinoCompareBundle\Repository\DinoDataRepository")
 */
class DinoData
{
    /**
     * @ORM\ManyToOne(targetEntity="FoodType", inversedBy="dinodata")
     */
    private $foodType;

    /**
     * @ORM\ManyToOne(targetEntity="Period", inversedBy="dinodata")
     */
    private $period;

    /**
     * @ORM\ManyToOne(targetEntity="DinoOrder", inversedBy="dinodata")
     */
    private $dinoOrder;

    /**
     * @ORM\ManyToOne(targetEntity="DinoSuborder", inversedBy="dinodata")
     */
    private $dinoSuborder;


    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=50, unique=true)
     */
    private $name;

    /**
     * @var float
     *
     * @ORM\Column(name="weight", type="float")
     */
    private $weight;

    /**
     * @var float
     *
     * @ORM\Column(name="lenght", type="float")
     */
    private $lenght;

    /**
     * @var float
     *
     * @ORM\Column(name="height", type="float")
     */
    private $height;

    /**
     * @var int
     *
     * @ORM\Column(name="discoverYear", type="integer")
     */
    private $discoverYear;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string")
     */
    private $path;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getFoodType()
    {
        return $this->foodType;
    }

    /**
     * @param mixed $foodType
     */
    public function setFoodType($foodType)
    {
        $this->foodType = $foodType;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return DinoData
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @return mixed
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * @param mixed $period
     */
    public function setPeriod($period)
    {
        $this->period = $period;
    }

    /**
     * Set weight
     *
     * @param float $weight
     * @return DinoData
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;

        return $this;
    }

    /**
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @param string $path
     */
    public function setPath($path)
    {
        $this->path = $path;
    }

    /**
     * Get weight
     *
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Set lenght
     *
     * @param float $lenght
     * @return DinoData
     */
    public function setLenght($lenght)
    {
        $this->lenght = $lenght;

        return $this;
    }

    /**
     * Get lenght
     *
     * @return float
     */
    public function getLenght()
    {
        return $this->lenght;
    }

    /**
     * Set height
     *
     * @param float $height
     * @return DinoData
     */
    public function setHeight($height)
    {
        $this->height = $height;

        return $this;
    }

    /**
     * Get height
     *
     * @return float
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Set discoverYear
     *
     * @param integer $discoverYear
     * @return DinoData
     */
    public function setDiscoverYear($discoverYear)
    {
        $this->discoverYear = $discoverYear;

        return $this;
    }

    /**
     * Get discoverYear
     *
     * @return integer
     */
    public function getDiscoverYear()
    {
        return $this->discoverYear;
    }

    /**
     * @return mixed
     */
    public function getDinoOrder()
    {
        return $this->dinoOrder;
    }

    /**
     * @param mixed $dinoOrder
     */
    public function setDinoOrder($dinoOrder)
    {
        $this->dinoOrder = $dinoOrder;
    }

    /**
     * @return mixed
     */
    public function getDinoSuborder()
    {
        return $this->dinoSuborder;
    }

    /**
     * @param mixed $dinoSuborder
     */
    public function setDinoSuborder($dinoSuborder)
    {
        $this->dinoSuborder = $dinoSuborder;
    }

    public function getWebPath()
    {
        return 'photo/' . $this->path;
    }

}

src/DinoCompareBundle/Form/DinoDataType.php
<?php

namespace DinoCompareBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DinoDataType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', array('label' => 'Nazwa:'))
            ->add('weight', 'text', array('label' => 'Waga:'))
            ->add('lenght', 'text', array('label' => 'Długość:'))
            ->add('height', 'text', array('label' => 'Wysokość:'))
            ->add('discoverYear', 'text', array('label' => 'Odkryty w:'))
            ->add('foodtype', EntityType::class, array(
                'class' => 'DinoCompareBundle:FoodType',
                'choice_label' => 'name', 'label' => 'Typ:'))
            ->add('period', EntityType::class, array(
                'class' => 'DinoCompareBundle:Period',
                'choice_label' => 'name','label' => 'Okres:'))
            ->add('dinoOrder', EntityType::class, array(
                'class' => 'DinoCompareBundle:DinoOrder',
                'choice_label' => 'name', 'label' => 'Rząd:'))
            ->add('dinoSuborder', EntityType::class, array(
                'class' => 'DinoCompareBundle:DinoSuborder',
                'choice_label' => 'name', 'label' => 'Podrząd:'))
            ->add('path', FileType::class, array('data_class' => null))
            ->add('save', 'submit', array('label' => 'Zapisz'))
            ;

        if ($options['noPhoto']) {
            $builder->remove('path');
        }

        if ($options['onlyPhoto']) {
            $builder->remove('name')
                    ->remove('weight')
                    ->remove('lenght')
                    ->remove('height')
                    ->remove('discoverYear')
                    ->remove('foodtype')
                    ->remove('period')
                    ->remove('dinoOrder')
                    ->remove('dinoSuborder');
        }
    }

    public function getName()
    {
        return '';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'DinoCompareBundle\Entity\DinoData',
            'noPhoto' => false,
            'onlyPhoto' => false
        ));
    }
}

//

src/DinoCompareBundle/Controller/DinoDataController.php
<?php

namespace DinoCompareBundle\Controller;

use DinoCompareBundle\Entity\DinoData;
use DinoCompareBundle\Form\DinoDataType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class DinoDataController extends Controller
{
    /**
     * @Route("/entrance")
     */
    public function entranceAction()
    {
        return $this->render('DinoCompareBundle:DinoData:entrance.html.twig', array());
    }

    /**
     * @Route("/create", name="createDino")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function createAction(Request $request)
    {
        $dino = new DinoData();
        $form = $this->createForm(DinoDataType::class, $dino);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            $dino = $form->getData();
            $file = $dino->getPath();
            $fileName = md5(uniqid()) . '.' . $file->guessExtension();

            $file->move(
                $this->getParameter('path_directory'),
                $fileName
            );

            $dino->setPath($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($dino);
            $em->flush();

            return new Response("Dodano nowego Dinozaura");
        }
        return $this->render('DinoCompareBundle:DinoData:create.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/edit/{id}")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function editAction(Request $request, $id)
    {
        $dinoRepository = $this->getDoctrine()->getRepository('DinoCompareBundle:DinoData');
        $dino = $dinoRepository->find($id);

        if (!$dino) {
            throw new NotFoundHttpException('Nie znaleziono dinozaura o podanym ID');
        }

        $form = $this->createForm(new DinoDataType(), $dino, array(
            'noPhoto' => true
        ));

        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            $dino = $form->getData();
            $file = $dino->getPath();
            $dino->setPath($file);

            $em = $this->getDoctrine()->getManager();
            $em->persist($dino);
            $em->flush();
        }
        return $this->render('DinoCompareBundle:DinoData:edit.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Route("/delete/{id}")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function deleteAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $dino = $em->getRepository('DinoCompareBundle:DinoData')->find($id);

        if (!$dino) {
            throw new NotFoundHttpException('Nie znaleziono dinozaura o podanym ID');
        }

        $em->remove($dino);
        $em->flush();

        return new Response("Usunięto dinozaura");
    }

    /**
     * @Route("/showAll", name="showAll")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function showAll(Request $request)
    {
        $dinoRepository = $this->getDoctrine()->getRepository('DinoCompareBundle:DinoData');
        $dinos = $dinoRepository->findBy(
            array(),
            array('name' => 'ASC')
        );

        $text = $request->get('text');

        if (isset($text)) {

            $em = $this->getDoctrine()->getManager();
            $dinos = $em->getRepository('DinoCompareBundle:DinoData')->findDinoByName($text);

            return $this->render('DinoCompareBundle:DinoData:showAll.html.twig', array('dinos' => $dinos));
        }
        return $this->render('DinoCompareBundle:DinoData:showAll.html.twig', array('dinos' => $dinos));
    }

    /**
     * @Route("/compareForm", name="compare")
     * @Method("POST")
     */
    public function compareForm(Request $request)
    {
        $session = $request->getSession();

        if ($session->has('firstDino')) {
            $session->remove('firstDino');
        }

        if ($session->has('secondDino')) {
            $session->remove('secondDino');
        }

        $firstDinoName = $request->get('firstDinosaur');
        $secondDinoName = $request->get('secondDinosaur');
        $em = $this->getDoctrine()->getManager();
        $dinoRepository = $em->getRepository('DinoCompareBundle:DinoData');
        $firstDino = $dinoRepository->find($firstDinoName);
        $secondDino = $dinoRepository->find($secondDinoName);

        return $this->render('DinoCompareBundle:DinoData:compareForm.html.twig', array(
            'firstDino' => $firstDino, 'secondDino' => $secondDino
        ));
    }

    /**
     * @Route("/selectDino", name="selectDino")
     */
    public function selectDino(Request $request)
    {
        $session = $request->getSession();
        $dinoRepository = $this->getDoctrine()->getRepository('DinoCompareBundle:DinoData');
        $dinos = $dinoRepository->findAll();

        if ($session->has('firstDino')) {
            $session = $request->getSession();
            $firstDino = $session->get('firstDino');
            $firstDinoSelected = $dinoRepository->find($firstDino);
        } else {
            $firstDinoSelected = null;
        }

        if ($session->has('secondDino')) {
            $session = $request->getSession();
            $secondDino = $session->get('secondDino');
            $secondDinoSelected = $dinoRepository->find($secondDino);
            $session->remove('secondDino');
        } else {
            $secondDinoSelected = null;
        }

        return $this->render('DinoCompareBundle:DinoData:selectDino.html.twig', array(
            'dinos' => $dinos, 'firstDino' => $firstDinoSelected, 'secondDino' => $secondDinoSelected
        ));
    }

    /**
     * @Route("/graphicSelection/{id}", name="graphic")
     */
    public function graphicSelection($id)
    {

        $dinoRepository = $this->getDoctrine()->getRepository('DinoCompareBundle:DinoData');
        $dinos = $dinoRepository->findAll();
        $suborderRepository = $this->getDoctrine()->getRepository('DinoCompareBundle:DinoSuborder');
        $suborders = $suborderRepository->findAll();

        return $this->render('DinoCompareBundle:DinoData:graphicSelection.html.twig', array('dinos' => $dinos, 'suborders' => $suborders, 'selection' => $id));
    }

    /**
     * @Route("/selectSuborder/{id}/{selection}", name="selectSuborder")
     */
    public function selectSuborder(Request $request, $id, $selection)
    {
        $em = $this->getDoctrine()->getManager();
        $dinos = $em->getRepository('DinoCompareBundle:DinoData')->findByDinoSuborder($id);

        if (!$dinos) {
            throw new NotFoundHttpException('Nie znaleziono dinozaurów w bazie danych');
        }

        return $this->render('DinoCompareBundle:DinoData:selectSuborder.html.twig', array('dinos' => $dinos, 'selection' => $selection));
    }

    /**
     * @Route("/idSaveToSession/{id}/{selection}", name="idSaveToSession")
     */
    public function idSaveToSession(Request $request, $id, $selection)
    {
        $session = $request->getSession();

        if ($selection == 1) {
            $session->set('firstDino', $id);
        }

        if ($selection == 2) {
            $session->set('secondDino', $id);
        }
        return new RedirectResponse($this->generateUrl('selectDino'));
    }

    /**
     * @Route("/changePhoto/{id}", name="changePhoto")
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function changePhotoAction(Request $request, $id)
    {
        $dinoRepository = $this->getDoctrine()->getRepository('DinoCompareBundle:DinoData');
        $dino = $dinoRepository->find($id);
        $photoForm = $this->createForm(new DinoDataType(), $dino, array(
            'noPhoto' => false,
            'onlyPhoto' => true
        ));

        $photoForm->handleRequest($request);

        if ($photoForm->isSubmitted()) {

            $dino = $photoForm->getData();
            $file = $dino->getPath();
            $fileName = md5(uniqid()) . '.' . $file->guessExtension();

            $file->move(
                $this->getParameter('path_directory'),
                $fileName
            );

            $dino->setPath($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($dino);
            $em->flush();

            return new Response("Zmieniono zdjęcie Dinozaura");
        }

        return $this->render('DinoCompareBundle:DinoData:changePhoto.html.twig', array(
            'dino' => $dino,
            'form' => $photoForm->createView()
        ));
    }

    /**
     * @Route("/adminLogin", name="adminLogin")
     * @Security("has_role('ROLE_ADMIN')")
     * Method("post")
     */
    public function adminLoginAction()
    {
        return $this->render('DinoCompareBundle:DinoData:adminLogin.html.twig', array());
    }
}

src/DinoCompareBundle/Resources/views/DinoData/adminLogin.html.twig
{% extends "::base.html.twig" %}

{% block title %}Admin Login Form{% endblock %}

{% block body %}
    <a href="create">
        <div>
            <p>Dodaj nowego Dinozaura</p>
        </div>
    </a>
    <a href="showAll">
        <div>
            <p>Pokaż wszystkie dinozaury</p>
        </div>
    </a>
    <a href="selectDino">
        <div>
            <p>Porównaj dinozaura</p>
        </div>
    </a>
{% endblock %}

src/DinoCompareBundle/Resources/views/DinoData/changePhoto.html.twig
{% extends "::base.html.twig" %}

{% block title %}Edit Dino{% endblock %}

{% block body %}
    <h1 class="mainPageTitle">Załadowane zdjęcie:</h1>
    <img src='{{ asset( dino.getWebPath ) }}' width="400" height="320">

    <h1 class="mainPageTitle">Zmień zdjęcie:</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

src/DinoCompareBundle/Resources/views/DinoData/compareForm.html.twig
{% extends "::base.html.twig" %}

{% block title %}Porównywarka Dinozaurów{% endblock %}

{% block body %}
    {% block topPanel %}
    {% endblock %}
    <div id="topPanel">
        <a href="{{ asset("selectDino") }}">Nowe porównanie</a>
    </div>
    <div class="col-md-12"><h1 id="title">Porównywarka Dinozaurów</h1></div>
    <table class="dinoTable" class="col-md-12" id="photoCompare">
        <th>{{ firstDino.name }}</th>
        <th>{{ secondDino.name }}</th>
        <tr>
            <td class="dinoPhoto"><img src="{{ firstDino.webPath }}" width="460" height="310" class="wrapper"></td>
            <td class="dinoPhoto"><img src="{{ secondDino.webPath }}" width="460" height="310" class="wrapper"></td>
        </tr>
    </table>
    {#{{ graphicPresentation }}#}
        {#---------------------------------------------------------------------------------------------------#}
    <table class="dinoTable" class="col-md-12" style="border-spacing: 22px;">
        <tr id="weight">
            <td class="firstDinoRow">
                {% if firstDino.weight+secondDino.weight < 1000 %}
                    {% set mediana = (((firstDino.weight + secondDino.weight) / 10)|round(0, 'ceil')) * 10 %}
                {% else %}
                    {% set mediana = (((firstDino.weight + secondDino.weight) / 1000)|round(0, 'ceil')) * 1000 %}
                {% endif %}
                {% set graphicPresentation = ((mediana - firstDino.weight) * 100) / mediana %}
                <div class="dinoProperty">{{ firstDino.weight }} kg.</div>
                <div class="progress180">
                    <div class="progress-bar180" percentValue="{{ graphicPresentation }}">
                    </div>
                </div>
                {% block progressBarLeftWeight %}
                    {{ parent() }}
                {% endblock %}
            </td>
            <td>
                <img src="" width="40" class="leftCup">
                <span class="compareType">Waga</span>
                <img src="" width="40" class="rightCup">
            </td>
            {% set graphicPresentation = (secondDino.weight * 100) / mediana %}
            <td>
                <div class="dinoProperty">{{ secondDino.weight }} kg.</div>
                <div class="progres">
                    <div class="progres-bar" percentValue="{{ graphicPresentation }}">
                        <span class="sr-only">70% Complete</span>
                    </div>
                </div>
                {% block progressBarRighttWeight %}
                    {{ parent() }}
                {% endblock %}
            </td>
        </tr>

        {#---------------------------------------------------------------------------------------------------#}


        <tr id="lenght">
            <td class="firstDinoRow">
                {% set mediana = (((firstDino.lenght + secondDino.lenght) / 2)|round(0, 'ceil'))*2 %}
                {% set graphicPresentation = ((mediana - firstDino.lenght) * 100) / mediana %}

                <div class="dinoProperty">{{ firstDino.lenght }} m.</div>
                <div class="progress180">
                    <div class="progress-bar180" percentValue="{{ graphicPresentation }}">
                    </div>
                </div>
                {% block progressBarLeftLenght %}
                    {{ parent() }}
                {% endblock %}
            </td>
            <td>
                <img src="" width="40" class="leftCup">
                <span class="compareType">Dlugosc</span>
                <img src="" width="40" class="rightCup">
            </td>
            {% set graphicPresentation = (secondDino.lenght * 100) / mediana %}
            <td>
                <div class="dinoProperty">{{ secondDino.lenght }} m.</div>
                <div class="progres">
                    <div class="progres-bar" percentValue="{{ graphicPresentation }}">
                        <span class="sr-only">70% Complete</span>
                    </div>
                </div>
                {% block progressBarRightLenght %}
                    {{ parent() }}
                {% endblock %}

            </td>
        </tr>

        {#---------------------------------------------------------------------------------------------------#}

        <tr id="height">
            <td class="firstDinoRow">
                {% set mediana = (((firstDino.height + secondDino.height) / 2)|round(0, 'ceil'))*2 %}
                {% set graphicPresentation = ((mediana - firstDino.height) * 100) / mediana %}
                <div class="dinoProperty">{{ firstDino.height }} m.</div>
                <div class="progress180">
                    <div class="progress-bar180" percentValue="{{ graphicPresentation }}">
                    </div>
                </div>
                {% block progressBarLeftHeight %}
                    {{ parent() }}
                {% endblock %}
            </td>
            <td>
                <img src="" width="40" class="leftCup">
                <span class="compareType">Wysokosc</span>
                <img src="" width="40" class="rightCup">
            </td>
            {% set graphicPresentation = (secondDino.height * 100) / mediana %}
            <td>
                <div class="dinoProperty">{{ secondDino.height }} m.</div>
                <div class="progres">
                    <div class="progres-bar" percentValue="{{ graphicPresentation }}">
                        <span class="sr-only">70% Complete</span>
                    </div>
                </div>
                {% block progressBarRightHeight %}
                    {{ parent() }}
                {% endblock %}
            </td>
        </tr>
        <tr>
            <td class="firstDinoRow">
                <div class="dinoProperty">{{ firstDino.discoverYear }} r.</div>
            </td>
            <td>Rok odkrycia</td>
            <td>
                <div class="dinoProperty">{{ secondDino.discoverYear }} r.</div>
            </td>
        </tr>
        <tr>
            <td class="firstDinoRow">
                <div class="dinoProperty">{{ firstDino.foodType.name }}</div>
            </td>
            <td>Typ</td>
            <td>
                <div class="dinoProperty">{{ secondDino.foodType.name }}</div>
            </td>
        </tr>
        <tr>
            <td class="firstDinoRow">
                <div class="dinoProperty">{{ firstDino.period.name }}</div>
            </td>
            <td>Okres</td>
            <td>
                <div class="dinoProperty">{{ secondDino.period.name }}</div>
            </td>
        </tr>
        <tr>
            <td class="firstDinoRow">
                <div class="dinoProperty">{{ firstDino.dinoOrder.name }}</div>
            </td>
            <td>Rząd</td>
            <td>
                <div class="dinoProperty">{{ secondDino.dinoOrder.name }}</div>
            </td>
        </tr>
        <tr>
            <td class="firstDinoRow">
                <div class="dinoProperty">{{ firstDino.dinoSuborder.name }}</div>
            </td>
            <td>Podrząd</td>
            <td>
                <div class="dinoProperty">{{ secondDino.dinoSuborder.name }}</div>
            </td>
        </tr>
    </table>
{% endblock %}

src/DinoCompareBundle/Resources/views/DinoData/create.html.twig
{% extends "::base.html.twig" %}

{% block title %}DinoCompareBundle:DinoData:create{% endblock %}

{% block body %}
<h1>Welcome to the DinoData:create page</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

src/DinoCompareBundle/Resources/views/DinoData/delete.html.twig
{% extends "::base.html.twig" %}

{% block title %}DinoCompareBundle:DinoData:delete{% endblock %}

{% block body %}
<h1>Welcome to the DinoData:delete page</h1>
{% endblock %}

src/DinoCompareBundle/Resources/views/DinoData/edit.html.twig
{% extends "::base.html.twig" %}

{% block title %}Edit Dino{% endblock %}

{% block body %}
    <h1 class="mainPageTitle">Zmień dane:</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

src/DinoCompareBundle/Resources/views/DinoData/entrance.html.twig
{% extends "::base.html.twig" %}

{% block title %}Edit Dino{% endblock %}

{% block body %}
    {% block topPanel %}
    {% endblock %}
    <a href="{{ asset('adminLogin') }}">
        <button>Admin</button>
    </a>
    <h1 class="mainPageTitle">PORÓWNYWARKA DINOZAURÓW</h1>
    <div id="mainPagePhotoContainer">
        <a href="{{ asset('selectDino') }}"><img src="/photo/but.jpg" width="700" id="entranceButton" class="zoom"></a>
        <h2 class="mainPageTitle">PORÓWNYWARKA DINOZAURÓW</h2>
    </div>
{% endblock %}

src/DinoCompareBundle/Resources/views/DinoData/new.html.twig
{% extends "::base.html.twig" %}

{% block title %}DinoCompareBundle:DinoData:new{% endblock %}

{% block body %}
    <h1>Welcome to the DinoData:new page</h1>
{% endblock %}

src/DinoCompareBundle/Resources/views/DinoData/selectDino.html.twig
{% extends "::base.html.twig" %}

{% block title %}Porównywarka Dinozaurów{% endblock %}

{% block body %}
    {% block topPanel %}
    {% endblock %}
    <div id="selectContainer">
        <h2>Wybierz dinozaury z listy</h2>
        <form method="post" action="{{ path('compare') }}">
            <div id="firstDinoSelect">
                <p>Wybierz dinozaura nr 1</p>
                <select name="firstDinosaur">
                    {% if firstDino is not null %}
                        <option value="{{ firstDino.id }}">
                            {{ firstDino.name }}
                        </option>
                    {% else %}
                        {% for dino in dinos %}
                            <option value="{{ dino.id }}">
                                {{ dino.name }}
                            </option>
                        {% endfor %}
                    {% endif %}
                </select>
                <a href="{{ path('graphic', {'id':1}) }}">Szukaj dinozaura...</a>
                {% if firstDino.webPath is defined %}
                    <div class="selectedDinoPhoto">
                        <img src="{{ firstDino.webPath }}" width="240" height="160">
                    </div>
                {% endif %}
            </div>
            <div id="seconDinoSelect">
                <p>Wybierz dinozaura nr 2</p>
                <select name="secondDinosaur">
                    {% if secondDino is not null %}
                        <option value="{{ secondDino.id }}">
                            {{ secondDino.name }}
                        </option>
                    {% else %}
                        {% for dino in dinos %}
                            <option value="{{ dino.id }}">
                                {{ dino.name }}
                            </option>
                        {% endfor %}
                    {% endif %}
                </select>
                <a href="{{ path('graphic', {'id':2}) }}">Szukaj dinozaura...</a>
                {% if secondDino.webPath is defined %}
                    <div class="selectedDinoPhoto">
                        <img src="{{ secondDino.webPath }}" width="240" height="160">
                    </div>
                {% endif %}
            </div>
            <hr>
            <p><input id="compareButton" type="submit" value="Porównaj"></p>
        </form>
    </div>
{% endblock %}